name: finbank_risk_lakehouse
version: "1.0.0"
config-version: 2

profile: finbank_postgres

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  finbank_risk_lakehouse:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
